name: flutter_payment_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^6.0.2
  flutter_facebook_auth: ^7.1.1
  google_sign_in: ^6.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/google_logo.png
    - lib/assets/images/photo.jpg
    - lib/assets/images/QR_Code_Scan.webp
    - lib/assets/images/facebook_logo.png
    - lib/assets/images/github_logo.png
    - lib/assets/images/ecg_logo.png
    - lib/assets/images/mtn_logo.png
    - lib/assets/images/netflix_logo.png